import cv2
import json
import os
import pickle

def show_stored_roi_on_frame(entry, target_key):
    """
    Loads the ROI for a specific target (face, paws, or pupil) 
    and displays it on the first frame of the corresponding video.
    Uses the '_reduced' video path where applicable.
    """
    original_path = entry['video']['mp4'].get(target_key)
    if not original_path:
        print(f"No video path found for {target_key}")
        return

    # Determine which video path was actually used during ROI selection
    # This logic matches how your analysis function determined the path
    if target_key in ['face', 'paws']:
        root, ext = os.path.splitext(original_path)
        video_path = f"{root}_reduced{ext}"
        if not os.path.exists(video_path): 
            video_path = original_path
    else:
        video_path = original_path

    # Determine the expected JSON file path
    root, _ = os.path.splitext(video_path)
    roi_json_path = f"{root}_roi.json"

    # --- Load ROI Data ---
    if not os.path.exists(roi_json_path):
        print(f"Error: ROI file not found at {roi_json_path}")
        return

    with open(roi_json_path, 'r') as f:
        roi_data = json.load(f)
    
    x, y, w, h = roi_data['x'], roi_data['y'], roi_data['w'], roi_data['h']
    
    # --- Capture Frame and Draw ROI ---
    cap = cv2.VideoCapture(video_path)
    ret, frame = cap.read()
    cap.release()

    if ret:
        # Draw the rectangle: top-left corner (x,y) and bottom-right corner (x+w, y+h)
        top_left_point = (int(x), int(y))
        bottom_right_point = (int(x + w), int(y + h))
        
        # Color is Green (B=0, G=255, R=0), Thickness is 2 pixels
        cv2.rectangle(frame, top_left_point, bottom_right_point, (0, 255, 0), 2)
        
        video_basename = os.path.basename(video_path)
        save_filename = f"ROI_Verification_{video_basename}.png"
        print(save_filename)
        cv2.imwrite(save_filename, frame)
        
        # Display the result
        win_name = f"ROI Verification: {target_key} on Reduced Video"
        cv2.imshow(win_name, frame)
        
        cv2.waitKey(0) # Wait indefinitely for a keypress to close the window
        cv2.destroyAllWindows()
    else:
        print("Error: Could not read the first frame from the video.")

# --- Example Usage ---
if __name__ == "__main__":
    # Load your data from the pickle file generated by your script
    with open("session_data.pkl", "rb") as f:
        loaded_data = pickle.load(f)
    
    # Assuming the 'animal' structure is a list, we use the first entry [0]
    first_animal_entry = loaded_data["animal"][0]

    # Display the ROI for the 'face' video
    print("Showing ROI for 'face' camera...")
    show_stored_roi_on_frame(first_animal_entry, target_key='face')
    
    # Display the ROI for the 'paws' video
    print("Showing ROI for 'paws' camera...")
    show_stored_roi_on_frame(first_animal_entry, target_key='paws')
    
    # Display the ROI for the 'paws' video
    print("Showing ROI for 'paws' camera...")
    show_stored_roi_on_frame(first_animal_entry, target_key='pupil')

